plugins {
    id 'com.android.application'
}

def getGitSha() {
    try {
        def text = 'git rev-parse --short HEAD'.execute().text.trim()
        return text.isEmpty() ? "N/A" : text
    } catch (Exception e) {
        return "N/A"
    }
}

def getGitShaFull() {
    try {
        def text = 'git rev-parse HEAD'.execute().text.trim()
        return text.isEmpty() ? "N/A" : text
    } catch (Exception e) {
        return "N/A"
    }
}

def getGitTag() {
    try {
        def text = 'git describe --tags'.execute().text.trim()
        return text.isEmpty() ? "N/A" : text
    } catch (Exception e) {
        return "N/A"
    }
}

android {
    namespace 'com.example.jsonvalidator'
    compileSdk 34

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.example.jsonvalidator"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        
        buildConfigField "String", "BUILD_TIMESTAMP", "\"${new Date().format('yyyyMMdd.HHmmss', TimeZone.getTimeZone('Asia/Kolkata'))}\""
        buildConfigField "String", "GIT_SHA", "\"${getGitSha()}\""
        buildConfigField "String", "GIT_SHA_FULL", "\"${getGitShaFull()}\""
        buildConfigField "String", "GIT_TAG", "\"${getGitTag()}\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.6.2'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.6.2'
}
